// Colors.qml
pragma Singleton
import QtQuick

QtObject {
    // General colors
    readonly property color text: "#FBF1C7"
    readonly property color background: "#1d2021"
    readonly property color lighterBackground: "#504945"
    readonly property color border: "#BE850E"
    readonly property color white: "white"
    readonly property color transparent: "transparent"
    readonly property color black: "#1D2021"
    readonly property color red: "#CC241D"
    readonly property color accentYellow: "#D79921"
    readonly property color fgaccentBeige: "#EBDBB2"
    readonly property color accentGreen: "#B8BB26"
    readonly property color woodBrown: "#824524"
    // each variables is only used once in the qml config
    
    // mpris player
    readonly property color playersLabel: white //                                                              original color: "white"
    readonly property color playerPopupColor1: transparent //                                                   original color: "transparent"
    readonly property color playerPopupColor2: woodBrown // Mpris player background                             original color: "#824524"
    readonly property color playerPopupColor3: woodBrown // Mpris icon color                                    original color: "#824524"
    readonly property color playerPopupColor4: text // Mpris controller text (ex: librewolf/vlc)                original color: "#white"
    readonly property color playerPopupColor5: transparent //                                                   original color: "#transparent"
    readonly property color playerPopupColor6: text // Mpris title text                                         original color: "#white"
    readonly property color playerPopupColor7: text // Mpris album text                                         original color: "#white"
    readonly property color playerPopupColor8: text // Mpris album text                                         original color: "#white"
    readonly property color playerPopupColor9: text // Mpris curent time video/sound text                       original color: "#white"
    readonly property color playerPopupColor10: woodBrown // Mpris slider background                            original color: "#824524"
    readonly property color playerPopupColor11: accentGreen // Mpris slider line                                original color: "#8D804B"
    readonly property color playerPopupColor12: accentGreen // Mpris slider head                                original color: "#8D804B"
    readonly property color playerPopupColor13: text // Mpris lenght of video/sound text                        original color: "white"
    readonly property color menuCheckBoxChecked1: "#C5E3EE" //                                                  original color: "#C5E3EE"
    readonly property color menuCheckBoxChecked2: "#90ACAD" //                                                  original color: "#90ACAD"
    readonly property color menuCheckBoxShapePath: transparent //                                               original color: "transparent"
    readonly property color menuChildrenRevealerShapePath: transparent //                                       original color: "transparent"
    readonly property color menuItemColor1: lighterBackground //                                                original color: "#824524"
    readonly property color menuItemColor2: white //                                                            original color: "white"
    readonly property color menuItemColor3: "#bbbbbb" //                                                        original color: "#bbbbbb"
    readonly property color menuRadioButtonColor1: "#C5E3EE" //                                                 original color: "#C5E3EE"
    readonly property color menuRadioButtonColor2: "#90ACAD" //                                                 original color: "#90ACAD"
    readonly property color menuViewColor: "#824524" //                                                         original color: "#824524"
    readonly property color sysTrayColor1: transparent //                                                       original color: "transparent"
    readonly property color sysTrayColor2: white //                                                             original color: "transparent"
    readonly property color sysTrayColor3: lighterBackground // systray dropdown color                          original color: "#9B5B36"
    readonly property color barColor1: transparent //                                                           original color: "transparent"
    readonly property color barColor2: background // Left block bar background                                  original color: "#3B253F"
    readonly property color barColor3: border // Left block bar border                                          original color: "#BE850E"
    readonly property color barColor4: background // Right block bar background                                 original color: "#3B253F"
    readonly property color barColor5: border // Right block bar border                                         original color: "#BE850E"
    readonly property color powerColor1: black // Battery indicator empty color                                 original color: "black"
    readonly property color powerColor2: red //                                                                 original color: "red"
    readonly property color powerColor3: accentYellow // Battery indicator normal color                         original color: "#EEA939"
    readonly property color powerColor4: accentYellow // Battery indicator normal color                         original color: "#EEA939"
    readonly property color timeColor1: white //                                                                original color: "white"
    readonly property color tooltipColor1: transparent//                                                        original color: "transparent"
    readonly property color tooltipColor2: "#3B253F" //                                                         original color: "#3B253F"
    readonly property color tooltipBackupColor1: transparent //                                                 original color: "transparent"
    readonly property color tooltipBackupColor2: "#10ff0000" //                                                 original color: "#10ff0000"
    readonly property color tooltipBackupColor3: "#10ff0000" //                                                 original color: "#10ff0000"
    readonly property color tooltipBackupColor4: red //                                                         original color: "red"
    readonly property color volumeColor1: "#9B5B36" //                                                          original color: "#9B5B36"
    readonly property color volumeColor2: woodBrown //                                                          original color: "#824524"
    readonly property color volumeColor3: accentGreen // Volume slider bar unmuted                              original color: "#8D804B"
    readonly property color volumeColor4: accentGreen // Volume slider head unmuted and muted                   original color: "#8D804B"
    readonly property color workspacesColor1: "#C0DB4C" //                                                      original color: "#C0DB4C"
    readonly property color workspacesColor2: "#59622D" //                                                      original color: "#59622D"
    readonly property color ropeColor1: fgaccentBeige // Rope color                                             original color: "#DAC99B"
    readonly property color ropeColor2: transparent //                                                          original color: "transparent"
    readonly property color displayColor1: text // Notification's title color                                   original color: "#9292B6"
    readonly property color displayColor2: text // Notification's body color                                    original color: "#9292B6"
    readonly property color notifsOverlayColor1: transparent //                                                 original color: "transparent"
    readonly property color screenshotOverlayColor1: "#44000000" //                                             original color: "#44000000"
    readonly property color screenshotOverlayColor2: woodBrown //                                               original color: "#824524"
}
